exports.missing = {
  1: {
    A: ["Grief", "Personal Pain"],
    "A♯": ["Emotional Outbursts"],
    B: ["Blind obedience", "Spiritual abuse"],
    C: ["Abandonment", "Physical neglect"],
    "C♯": ["Lack of Harmony"],
    D: ["Neglect & or Rejection", "Emotional manipulation"],
    "D♯": ["Gloom & Severe Depression"],
    E: ["Repression", "Criticism"],
    F: ["Shame", "Humiliation"],
    G: ["Excessive Criticism", "Gossiping", "Sarcasm"],
    "G♯": ["Resentment"],
    "F♯": ["Lack of Success"],
  },
  2: {
    A: ["Lack of Understanding"],
    "A♯": ["Anger and Pain"],
    B: ["Loss of Enlightenment"],
    C: ["Insecurity"],
    "C♯": ["Regret", "Lack of joy"],
    D: ["Loss of Self Esteem", "Loss of Morality"],
    "D♯": ["Lack of Inner Strength"],
    E: ["Loss of will power", "Loss of Control"],
    F: ["Loss of love", "Loss of compassion", "Loss of hope"],
    G: ["Loss of Creativity", "Loss Of Expression"],
    "G♯": ["Lack of Energy"],
    "F♯": ["Difficult Situations"],
  },
  3: {
    A: ["Loss of concentration", "learning difficulties"],
    "A♯": ["Lack of joy", "Lack of  will power"],
    B: ["Lack of inspiration & purpose", "Over intellectualism", "Frustration"],
    C: ["Inability to relax", "Poor focus", "Suicidal tendencies"],
    "C♯": ["Stubbornness", "Unrest", "fear"],
    D: ["Emotional Numbness", "Lack of excitement/ Passion"],
    "D♯": ["Irritability", "Depression", "Impatience Activity"],
    E: ["Lack of judgement", "Inferiority complex", "Anger"],
    F: ["Grief", "Social stress"],
    G: ["Shy and Timid", "Introvert", "Quiet"],
    "G♯": ["Uneasiness", "Worry about a failed scheme", "Resentment"],
    "F♯": ["Emotionally Indecisive", "Discontent"],
  },
  4: {
    A: ["Loss of concentration", "learning difficulties", " Detachment ", " Extreme confusion", "Extremely Cold and Logical"],
    "A♯": ["Lack of joy", "Lack of  will power& determination", "Obsessiveness", "Self doubt", "Regret"],
    B: ["Lack of inspiration & purpose", "Over intellectualism", "Frustration", "Depression", "Stress and worry"],
    C: ["Insecurity", "Identity crisis", "Survival issues", "Weak Ego"],
    "C♯": ["Lack of Harmony", "Regrets", "Lack of joy", "Unrest", "Fear"],
    D: ["Emotional Numbness", "Lack of excitement/ Passion", "Loss of Self esteem", "Guilt"],
    "D♯": ["Gloom", "Depression", "Impatience", "Anxiety", "Distress"],
    E: ["Repression of feelings", "Loss of will power & Control", "Lack of judgement", "Inferiority complex", "Anger"],
    F: ["Shame", "Humiliation", "Loss of Love, hope, Compassion", "Grief", "Social stress"],
    G: ["Shy and Timid", "Introvert", "Quiet", "Lack of Creativity & Expression"],
    "G♯": ["Uneasiness", "Worry about a failed scheme", "Resentment", "Disgust", "Bitterness", "Disappointment"],
    "F♯": ["Emotionally Indecisive", "Discontent", "Basic negative attitude", "Pessimistic", "Gloomy", "Distrustful"],
  },
  5: {
    A: [
      "Migraines",
      "Gall Bladder Dysfunction",
      "Diseases of ovary in Females",
      "Pain in shoulders, hand and finger joints",
      " Illness of the Hip Joint, Knee Joint and Ankle joint",
    ],
    "A♯": ["Mouth ulcers", "Tooth illnesses", "Skin Allergies", "Weakness in upper legs and thighs"],
    B: ["Neurological disorders", "Recurring Headaches", "Lack of sleep", "Psychological Disturbances"],
    C: ["Auto-immune system", "Skeletal systems", "Joints below waist", "BP Disturbances", "Spinal Column", "Allergies due to Omega 7 Deficiency"],
    "C♯": ["Cervical Pain", "Heart Disturbances", "Weakness in Neck & Larynx", "Neuralgias of the shoulder and arm", "Upper wisdom teeth Pain"],
    D: ["Kidneys and Urinary Bladder", "Intestines", "Disorders of Ovaries and fallopian tubes in females", "Disorders of Testicles and Sperm in Males"],
    "D♯": ["Gall Bladder weakness", "Issues with Endocrine System", "Hormonal Imbalances", "Breathing problems."],
    E: ["Pancreas", "Stomach", "Liver", "Gall Bladder", "Muscles"],
    F: ["High Blood Pressure", "Heart Problems", "Shortness of breath", "Varicose veins"],
    G: ["Hormonal Imbalances", "Muscle cramps", "Kidney disorders", "Thyroid Dysfunction", "Parathyroid Dysfunction"],
    "G♯": [
      "Issues in Large Intestine",
      "Lower back problems due to muscular weakness",
      "Joint problems affecting knees and ankles",
      "Disturbances of blood circulation in the legs and feet",
    ],
    "F♯": ["Weakness of the digestive & Nervous system", "Problems with the spine", "Eye & Ear diseases", "Issues with Urinary Bladder"],
  },
  6: {
    A: ["Vitamin B5- Pantothenic acid", "Vitamin E", "Magnesium", "Cholesterol", "Triglycerides"],
    "A♯": ["Interleukin 6", "Valine", "Threonine", "Vitamin E"],
    B: ["Vitamin B 3-Niacin", "Vitamin B5- Pantothenic acid", "Vitamin H - Biotin"],
    C: ["Calcium", "Iron", "Omega 7 Fatty Acid"],
    "C♯": ["Vitamin B1", "Chloride", "Calcitonin", "Zinc", "Essential Fatty Acids"],
    D: ["Vitamin B1", "Vitamin A", "Ammonium"],
    "D♯": ["Calcium", "Potassium", "Dopamine", "Serotonin"],
    E: ["Thiamine", "Ribo-flavine", "Tri iodo Thyronine -T3", "Blood Sugar"],
    F: ["Vitamin C", "Troponin A", "Copper", "Zinc"],
    G: ["Vitamin D", "Dexamethasone", "Para thyroid Hormone", "Thyroid Hormones", "Magnesium", "Phosphates", "Calcium", "Calcitonin"],
    "G♯": ["Vitamin B6- Pyridoxine", "Magnesium", "Chromium", "Tryptophan"],
    "F♯": ["Vitamin B2- Riboflavine", "Insulin", "Sodium Ions", "Potassium  Ions"],
  },
};

exports.weak_problems = {
  1: {
    A: ["Grief", "Personal Pain"],
    "A♯": ["Emotional Outbursts"],
    B: [
      "Withheld information",
      "Forced religiosity",
      "Invalidation of one's beliefs",
      "Education that suppressed curiosity",
      "Blind obedience",
      "Misinformation",
      "Lies",
      "Spiritual abuse",
    ],
    C: [
      "Abandonment",
      "Physical neglect",
      "Poor physical bonding with mother,",
      "Malnourishment,",
      "Feeding difficulties,",
      "Major illness or surgery",
      "Physical abuse or violent relationship",
      "Poverty Conditions",
    ],
    "C♯": ["Lack of Harmony", "DNA Damage"],
    D: [
      "Neglect & or Rejection",
      "Sexual abuse",
      "Emotional abuse,",
      "Volatile situations,",
      "Coldness,",
      "Denial of child's feelings,",
      "Lack of mirroring,",
      "Enmeshment,",
      "Emotional manipulation",
      "Religious or moral severity",
      "Physical abuse",
      "Alcoholic families",
    ],
    "D♯": ["Gloom & Severe Depression"],
    E: ["Repression", "Criticism"],
    F: [
      "Shame",
      "Humiliation",
      "Authoritarianism",
      "Volatile situations",
      "Domination of will",
      "Physical abuse",
      "Dangerous environment",
      "Fear of punishment",
      "Age inappropriate responsibilities",
    ],
    G: [
      "Excessive Criticism",
      "Lies",
      "Verbal abuse",
      "Constant yelling",
      "Secrets (threats for telling)",
      "Authoritarianism (you don't talk back)",
      "Alcoholic, chemical dependent family or cults (when you don't talk, don't trust, don't feel).",
      "Blasphemy: Criticism of God",
      "Gossiping",
      "Sarcasm or angry words",
      "Display of hatred",
      "Gossiping",
    ],
    "G♯": ["Resentment"],
    "F♯": ["Lack of Success"],
  },
  2: {
    A: ["Lack of Understanding"],
    "A♯": ["Anger and Pain"],
    B: ["Loss of Enlightenment"],
    C: ["Insecurity"],
    "C♯": ["Regret", "Lack of joy", "Sexual tension", "Jealousy"],
    D: ["Loss of Self Esteem", "Loss of Morality", "Guilt"],
    "D♯": ["Lack of Inner Strength"],
    E: ["Loss of will power", "Loss of Control"],
    F: ["Loss of love", "Loss of compassion", "Loss of hope"],
    G: ["Loss of Creativity", "Loss Of Expression"],
    "G♯": ["Lack of Energy"],
    "F♯": ["Difficult Situations"],
  },
  3: {
    A: [
      "Loss of concentration",
      "Cynicism",
      "Detachment",
      "Intelligence deficit",
      "learning difficulties",
      "Afraid of success",
      "Extreme confusion",
      "Living in a fantasy world",
    ],
    "A♯": ["Lack of joy", "Lack of  will power", "Lack of Determination", "Loss of confidence", "Lack of serenity", "Loss of simplicity"],
    B: [
      "Aimlessness",
      "Lack of inspiration",
      "Lack of purpose.",
      "Over intellectualism",
      "Dissociation/ cut off from reality",
      "Senility",
      "Hesitation to serve",
      "Live in great fear.",
      "Spiritual ignorance",
      "No spark of joy",
      "Frustration",
      "Regret",
      "Sexual tension",
      "Jealousy",
      "Stubbornness",
      "Lack of joy",
    ],
    C: [
      "Inability to relax",
      "Worries",
      "Confusion",
      "Withdrawn state",
      "Poor focus",
      "Poor discipline",
      "Suspicious",
      "Inability to achieve goals",
      "Financial difficulties",
      "Suicidal tendencies",
    ],
    "C♯": ["Stubbornness", "Unrest", "fear", "pronounced grief"],
    D: [
      "Emotional Numbness",
      "Lack of excitement/ Passion",
      "Intimacy Issues( both giving and receiving) with Relation ship challenges",
      "Lack of vitality",
      "Lack of Energy",
      "Rigidity in body and attitude",
      "Self negating",
    ],
    "D♯": ["Irritability", "Nervous ness", "Insomnia", "Depression", "Impatience", "Intense Activity"],
    E: [
      "Indecisiveness",
      "Lack of clarity",
      "Lack of judgement",
      "Lack of self worth",
      "Inferiority complex",
      "Anger",
      "Blaming",
      "Fragile determination",
      "Shrinking courage",
      "Inner void",
    ],
    F: ["Low energy", "Anxiety", "Despair", "Sorrow", "Grief", "Social stress", "Attraction towards stimulants"],
    G: [
      "Shy and Timid",
      "Introvert",
      "Quiet",
      "Have a small weak voice",
      "Fear of speaking",
      "Inconsistent approach",
      "Unreliable",
      "Loss of expression",
      "Difficulty in putting feelings into words",
      "Doubt",
      "Fear",
      "Uncertainty",
      "Habitual  lying",
    ],
    "G♯": ["Uneasiness", "Worry about a failed scheme", "Bad-tempered gnashing of teeth", "Resentment and dislike"],
    "F♯": ["Emotionally Indecisive", "Resentment", "Discontent", "Low Sex Drive"],
  },
  4: {
    A: ["Loss of concentration", "learning difficulties", " Detachment ", " Extreme confusion", "Extremely Cold and Logical"],
    "A♯": ["Lack of joy", "Lack of  will power& determination", "Obsessiveness", "Self doubt", "Regret"],
    B: ["Lack of inspiration & purpose", "Over intellectualism", "Frustration", "Depression", "Stress and worry"],
    C: ["Insecurity", "Identity crisis", "Survival issues", "Weak Ego"],
    "C♯": ["Lack of Harmony", "Regrets", "Lack of joy", "Unrest", "Fear"],
    D: ["Emotional Numbness", "Lack of excitement/ Passion", "Loss of Self esteem", "Guilt"],
    "D♯": ["Gloom", "Depression", "Impatience", "Anxiety", "Distress"],
    E: ["Repression of feelings", "Loss of will power & Control", "Lack of judgement", "Inferiority complex", "Anger"],
    F: ["Shame", "Humiliation", "Loss of Love, hope, Compassion", "Grief", "Social stress"],
    G: ["Shy and Timid", "Introvert", "Quiet", "Lack of Creativity & Expression"],
    "G♯": ["Uneasiness", "Worry about a failed scheme", "Resentment", "Disgust", "Bitterness", "Disappointment"],
    "F♯": ["Emotionally Indecisive", "Discontent", "Basic negative attitude", "Pessimistic", "Gloomy", "Distrustful"],
  },
  5: {
    A: [
      "Migraines",
      "Gall Bladder Dysfunction",
      "Diseases of ovary in Females",
      "Pain in shoulders, hand and finger joints",
      " Illness of the Hip Joint, Knee Joint and Ankle joint",
    ],
    "A♯": ["Mouth ulcers", "Tooth illnesses", "Skin Allergies", "Weakness in upper legs and thighs"],
    B: ["Neurological disorders", "Recurring Headaches", "Lack of sleep", "Psychological Disturbances"],
    C: ["Auto-immune system", "Skeletal systems", "Joints below waist", "BP Disturbances", "Spinal Column", "Allergies due to Omega 7 Deficiency"],
    "C♯": ["Cervical Pain", "Heart Disturbances", "Weakness in Neck & Larynx", "Neuralgias of the shoulder and arm", "Upper wisdom teeth Pain"],
    D: ["Kidneys and Urinary Bladder", "Intestines", "Disorders of Ovaries and fallopian tubes in females", "Disorders of Testicles and Sperm in Males"],
    "D♯": ["Gall Bladder weakness", "Issues with Endocrine System", "Hormonal Imbalances", "Breathing problems."],
    E: ["Pancreas", "Stomach", "Liver", "Gall Bladder", "Muscles"],
    F: ["High Blood Pressure", "Heart Problems", "Shortness of breath", "Varicose veins"],
    G: ["Hormonal Imbalances", "Muscle cramps", "Kidney disorders", "Thyroid Dysfunction", "Parathyroid Dysfunction"],
    "G♯": [
      "Issues in Large Intestine",
      "Lower back problems due to muscular weakness",
      "Joint problems affecting knees and ankles",
      "Disturbances of blood circulation in the legs and feet",
    ],
    "F♯": ["Weakness of the digestive & Nervous system", "Problems with the spine", "Eye & Ear diseases", "Issues with Urinary Bladder"],
  },
  6: {
    A: ["Vitamin B5- Pantothenic acid", "Vitamin E", "Magnesium", "Cholesterol", "Triglycerides"],
    "A♯": ["Interleukin 6", "Valine", "Threonine", "Vitamin E"],
    B: ["Vitamin B 3-Niacin", "Vitamin B5- Pantothenic acid", "Vitamin H - Biotin"],
    C: ["Calcium", "Iron", "Omega 7 Fatty Acid"],
    "C♯": ["Vitamin B1", "Chloride", "Calcitonin", "Zinc", "Essential Fatty Acids"],
    D: ["Vitamin B1", "Vitamin A", "Ammonium"],
    "D♯": ["Calcium", "Potassium", "Dopamine", "Serotonin"],
    E: ["Thiamine", "Ribo-flavine", "Tri iodo Thyronine -T3", "Blood Sugar"],
    F: ["Vitamin C", "Troponin A", "Copper", "Zinc"],
    G: ["Vitamin D", "Dexamethasone", "Para thyroid Hormone", "Thyroid Hormones", "Magnesium", "Phosphates", "Calcium", "Calcitonin"],
    "G♯": ["Vitamin B6- Pyridoxine", "Magnesium", "Chromium", "Tryptophan"],
    "F♯": ["Vitamin B2- Riboflavine", "Insulin", "Sodium Ions", "Potassium  Ions"],
  },
};

exports.chakra_mapping = {
  C: ["Root", "#EC1C24"],
  D: ["Sacral", "#F4811E"],
  E: ["Solar", "#FDF001"],
  F: ["Heart", "#0C8F4D"],
  G: ["Throat", "#19ADEF"],
  A: ["Third Eye", "#2F3093"],
  B: ["Crown", "#A64686"],
};

exports.chakra_mapping_recommendations = {
  weak: {
    root: ["Sound Therapy sessions", "Subliminal Affirmations", "Subliminal Switch words", "Brain waves"],
    sacral: ["Sound Therapy sessions", "Subliminal Affirmations", "Subliminal Switch words", "Brain waves"],
    solar: ["Sound Therapy sessions", "Subliminal Affirmations", "Subliminal Switch words", "Brain waves"],
    heart: ["Sound Therapy sessions", "Subliminal Affirmations", "Subliminal Switch words", "Brain waves"],
    throat: ["Sound Therapy sessions", "Subliminal Affirmations", "Subliminal Switch words", "Brain waves"],
    "third eye": ["Sound Therapy sessions", "Subliminal Affirmations", "Subliminal Switch words", "Brain waves"],
    crown: ["Sound Therapy sessions", "Subliminal Affirmations", "Subliminal Switch words", "Brain waves"],
  },
  hyperactive: {
    root: ["Root Chakra Guided Meditation", "Brain waves", "Bach Flower Remedies"],
    sacral: ["Sacral Chakra Guided Meditation", "Brain waves", "Bach Flower Remedies"],
    solar: ["Solar Plexus Chakra Guided Meditation", "Brain waves", "Bach Flower Remedies"],
    heart: ["Heart Chakra Guided Meditation", "Forgiveness or Hoponopono Prayer", "Brain waves", "Bach Flower Remedies"],
    throat: ["Throat Chakra Guided Meditation", "Brain waves", "Bach Flower Remedies"],
    "third eye": ["Third eye Chakra Guided Meditation", "Brain waves", "Bach Flower Remedies"],
    crown: ["Crown  Chakra Guided Meditation", "Brain waves/ Bach Flower Remedies"],
  },
};

exports.normal_mapping = {
  A: ["Charismatic", "Knowledgeable", "Intuitive", "Master of Self"],
  "A♯": ["Trustworthy", "Honest", "Open to suggestions", "Balanced"],
  B: ["Peaceful", "Refined", "Joyful", "Grateful"],
  C: ["Grounded", "Prideful ", "Independent", "Determined"],
  "C♯": ["Relaxed", "Generous", "Restful", "In Harmony"],
  D: ["Empathetic", "High Self Esteem", "Emotionally  complete", "morality bound"],
  "D♯": ["Benevolent", "Kind Hearted", "Joyful", "Hopeful"],
  E: ["Cheerful", "Outgoing", "Respectful", "Expressive"],
  F: ["Compassionate", "Humanitarian", "Generous", "Nurturing"],
  "F♯": ["Contented", "Optimistic", "Trustworthy", "Focussued "],
  G: ["Good Speaker", "Sincere", "Truthful", "Independent"],
  "G♯": ["Fairness", "Openness", "Confident", "Trustworthy"],
};

exports.hyperactive_mapping = {
  1: {
    A: ["Over confidence"],
    "A♯": ["Repression emotions and feelings", "Criticism"],
    B: ["Excessive Compassion", "Enlightenment"],
    C: ["Habitual fear", "Resentment"],
    "C♯": ["Loss Of Creativity"],
    D: ["Excessive Resentment", "Lack of Energy"],
    "D♯": ["Gloom & Severe Depression"],
    E: ["Anger and Pain"],
    F: ["Shame", "Humiliation"],
    G: ["Excess Talk", "Verbal Chatter"],
    "G♯": ["Resentment", "Loss of Intimacy"],
    "F♯": ["Lack of Success", "Survival Issues"],
  },
  2: {
    A: [],
    "A♯": ["Excessive Acceptance"],
    B: [],
    C: ["Uncaring of others Feelings"],
    "C♯": ["Excessive Compassion"],
    D: ["Emotional Dependency", "Over sensitive"],
    "D♯": ["Over joyousness", "Over contented"],
    E: ["Perfectionism"],
    F: ["Excessive love", "Excessive compassion", "Excessive hope"],
    G: ["Arrogancy", "Self Righteousness"],
    "G♯": ["Excessive Energy"],
    "F♯": ["Constant Power Seeking"],
  },
  3: {
    A: ["Egoist", "Proud"],
    "A♯": ["Excessive Joy", "Heightened Will Power"],
    B: ["Sense of Frustration", "Full of Despair"],
    C: ["Sluggishness", "Confusion"],
    "C♯": ["Over contended", "Over joyousness"],
    D: ["Excess of Passion"],
    "D♯": ["Excessive Optimistic", "Intense Activity"],
    E: ["Stubborn", "Being overly critical"],
    F: ["Over confidence", "Jealous"],
    G: ["Excessive Talking", "Sensitive to Criticism"],
    "G♯": ["Excessive Love", "Excessive Respect"],
    "F♯": ["Explosive & Agressive approach"],
  },
  4: {
    A: ["Cold Behaviour", "Bitterness", "Excessive Display of Fears and Phobias", "Proud"],
    "A♯": ["Excessive Joy", "Heightened Will Power", "Over Determination", "Too Much Speaking for Self"],
    B: [" Excessive Compassion", "Enlightenment", "Sense of Frustration", "Depression"],
    C: ["Uncaring of others Feelings", "Inability to relax", "Sluggishness", "Confusion"],
    "C♯": ["Over contended", "Over joyousness", "Over Yielding", "Over Generous"],
    D: ["Excess of Passion", "Manic", "Excitement", "Overtly Proud", "Constant Power seeking"],
    "D♯": ["Over joyousness", "Over contented", "Excessive Optimistic", "Too much Inquisitive"],
    E: ["Stubborness", "Perfectionism", "Addiction to security", "Superiority complex"],
    F: ["Over confidence", "Over serenity", "Extremely Possessive", "Overtly Critical"],
    G: [" Traditional ", "Indecisiveness", "Sensitive to Criticism", "Undue display of authority"],
    "G♯": ["Excessive Love", "Excessive Respect", "Mania", "Anxiety"],
    "F♯": ["Explosive", "Insulting Others always", "Self serving", "Arrogant"],
  },
  5: {
    A: [
      "Imbalances of The Endocrine System",
      "Hormonal Stress",
      "Problems In The Knees & Cartilage's",
      "Migraine headaches",
      "Vertigo",
      "Deafness",
      "Tinnitus",
      "Paranoia",
      "Delusions",
      "Hallucinations",
    ],
    "A♯": [
      "Epigastric pain,",
      "Flatulence",
      "Inflammation Of The Lung /Bronchus.",
      "Swelling of legs, feet and joints.",
      "General fatigue, especially in the limbs.",
    ],
    B: [
      "Chest discomfort",
      "Palpitations",
      "Inflammation Of The Liver",
      "Imbalances Of The Nervous System",
      "Irritation of Endocrinal System",
      "Headache",
      "Blurred vision",
    ],

    C: [
      "cervical Pain",
      "Stiff Neck",
      "Hearing Problems, Deafness, Tinnitus",
      "Fever like conditions",
      "Diarrhea, constipation, abdominal pain and distention.",
      "distending pain in lower abdomen referring to the back",
    ],
    "C♯": [
      "HEART",
      "Palpitations",
      "Tongue/mouth ulcers",
      "Restlessness",
      "Bitter taste in the mouth",
      "Inner arm pain",
      "Weak wrists.",
      "Carpel tunnel syndrome",
    ],
    D: [
      "Acidity",
      "Irritation of Pharynges.",
      "Neck stiffness and swelling.",
      "Sinusitis",
      "Associated Lung complaints like asthma, bronchitis",
      "urinary issues",
      "kidney problems",
      "lower back pain",
      "gynecological problems in females",
    ],
    "D♯": [
      "Vertebrae pain",
      "Endocrine glands Imbalances",
      "Inflammation Of The Gall Bladder",
      "Imbalances in Blood Pressure",
      "Breathing Problems",
      "Allergies",
      "Environmental Sensitivities Asthma",
    ],
    E: [
      "Fever & chills",
      "Boody ache,",
      "scratchy throat",
      "Sweating",
      "headache",
      "Shortness of breath and shallow breathing",
      "Fatigue",
      "Frequent cold and flu",
      "Allergies",
      "Dry skin",
      "Pain in shoulders, back and supraclavicular fossa",
      "Tennis elbow, Stiff forearm.",
      "Wrist disorders, Carpal tunnel syndrome.",
    ],
    F: [
      "HEART",
      "Palpitations",
      "Tongue/mouth ulcers",
      "Night Sweats",
      "Chest oppression",
      "Digestive Problems",
      "Hiatus Hernia",
      "Breast distension",
      "Menstrual pain in females",
      "Headache",
      "Abdominal pain",
    ],
    G: [
      "Chronic sore throat & colds",
      "Imbalance Of The Bones",
      "Muscle Tension",
      "Irritation Of The Liver Function",
      "Problems Of The Feet",
      "Lower Legs / Muscle Cramps",
      "Imbalances Of The Liver",
      "Fat intolerance",
      "Blurred vision",
      "Chronic diarrhea/constipation",
      "Imbalances of Thyroid & Parathyroid Glands",
    ],
    "G♯": [
      "Regurgitation a/or vomiting likely after eating,",
      "Burning sensation in the epigastrium,",
      "Nausea",
      "Belching",
      "Hiccups",
      "Varicose veins: Lower Limbs",
      "Joint Problems: Knees and Ankles",
      "Disturbed Blood and Lymphatic Circulation in Legs and Feet",
    ],
    "F♯": [
      "EYE PROBLEMS",
      "EAR PROBLEMS",
      "Tendency To Ear Infections.",
      "NOSE PROBLEMS",
      "Runny nose",
      "Nose bleeding and",
      "Nasal congestion.",
      "Headaches,",
      "Nape of neck stiffness,",
      "Pain and stiffness along spine, hip, knee, leg, foot, small toe",
    ],
  },
  6: {
    A: [
      "Vitamin Imbalances",
      "Vitamin B5- Pantothenic acid",
      "Vitamin E",
      "Neuro transmitters Imbalances:",
      "Epinephrine",
      "Histamine",
      "Hormone Imbalances:",
      "Glucagon",
      "TRH",
      "Leukotriene E4",
      "Mineral Imbalances",
      "Magnesium",
      "Chromium",
      "Amino Acid Imbalances:",
      "Tryptophan",
      "Excess of:",
      "Cholesterol",
      "Triglycerides",
    ],
    "A♯": [
      "Vitamin Excess",
      "Vitamin B5- Pantothenic acid",
      "Vitamin E",
      "Vitamin K1",
      "Neuro transmitters Excess:",
      "Interleukin 1",
      "Interleukin 2",
      "Interleukin 6",
      "Hormone Excess:",
      "Melatonin",
      "Somatomedins",
      "Leutinising Hormone",
      "Amino Acid Excess:",
      "Valine",
      "Threonine",
    ],
    B: [
      "Vitamin Excess",
      "Vitamin B 3-Niacin",
      "Vitamin B5- Pantothenic acid",
      "Vitamin H - Biotin",
      "Vitamin K1",
      "Mineral  Excess",
      "Gold",
      "Hormone Excess:",
      "Leukotriene B4",
      "Oxytocin",
      "Amino Acid Excess:",
      "Cysteine",
    ],
    C: [
      "Amino Acid Excess",
      "Lysine",
      "Isoleucine",
      "Aspargine",
      "Aspartic Acid",
      "Vitamin Excess :",
      "Vitamin A",
      "Biotin",
      "Mineral Excess",
      "Calcium",
      "Iron",
      "Neuro transmitters Excess:",
      "Adenosine",
      "Bradykinin",
      "Pipecolic Acid",
      "Vasopressin",
    ],
    "C♯": [
      "Vitamin Excess:",
      "Vitamin BI",
      "Vitamin A",
      "Mineral Excess",
      "Chloride",
      "Neuro transmitters Excess :",
      "Endorphins",
      "Enkephalins",
      "Hormone Excess:",
      "Calcitonin",
      "Omega 3 fatty acid",
      "Calcitonin",
      "Essential Fatty Acids",
    ],
    D: [
      "Amino Acid Imbalances:",
      "Lysine",
      "Methionine",
      "Glutamine",
      "Glutamic  Acid",
      "Vitamin Imbalances:",
      "Vitamin BI",
      "Vitamin A",
      "Vitamin K2",
      "Mineral Imbalances:",
      "Ammonium",
      "Neuro transmitters deficiency:",
      "Acetyl Choline",
      "Hormone Deficiency:",
      "DHEA",
      "LH-RH",
      "Testosterone",
    ],
    "D♯": [
      "Amino Acid Imbalances:",
      "Histidine",
      "Mineral Imbalances:",
      "Calcium",
      "Pottasium",
      "Neuro transmitters Imbalance:",
      "Dopamine",
      "Nor Epinephrine",
      "Tryptamine",
      "Hormone Imbalance:",
      "Leukotriene A4",
      "Pregnenolone",
    ],
    E: [
      "Vitamin Excess",
      "Thiamine",
      "Ribo flavine",
      "Vitamin k2",
      "Amino Acid Excess:",
      "Phenylalanine",
      "Neuro transmitters Excess:",
      "Epinephrine",
      "Leukotriene B4",
      "Hormone Excess:",
      "Deoxy-Corticosterone",
      "Tri iodo Thyronine -T3",
      "Cyclic -AMP",
    ],
    F: [
      "Vitamin Imbalances",
      "Vitamin C",
      "Vitamin k3",
      "Amino Acid Imbalances:",
      "Arginine",
      "Alanine",
      "Neuro transmitters Imbalances:",
      "Endorphins",
      "Hormone Imbalances:",
      "Prostaglandin E1",
      "Prostaglandin F2 Alpha",
      "Prolactin",
      "Prednisolone",
      "Somatotrophin ( Growth Hormone)",
      "Mineral  Imbalances",
      "Copper",
      "Zinc",
    ],
    G: [
      "Vitamin Excess",
      "Vitamin D",
      "Vitamin U",
      "Neuro transmitters Excess:",
      "Dynorphin",
      "Hormone Excess:",
      "Dexamethasone",
      "Progesteron",
      "Para thyroid Hormone",
      "Thyroxin -T4",
      "Mineral Excess",
      "Magnesium",
      "Phosphates",
      "Calcium",
    ],
    "G♯": [
      "Vitamin Imbalances",
      "Vitamin B6- Pyridoxine",
      "Neuro transmitters Imbalances:",
      "GABA",
      "Epinephrine",
      "Hormone Imbalances:",
      "Growth Hormone Relesing Factor",
      "Mineral Imbalances",
      "Magnesium",
      "Chromium",
      "Amino Acid Imbalances:",
      "Tryptophan",
    ],
    "F♯": [
      "Vitamin Imbalances",
      "Vitamin B2- Riboflavine",
      "Amino Acid Imbalances:",
      "Tyrosine",
      "Neuro transmitters Imbalances:",
      "Epinephrine",
      "Hormone Imbalances:",
      "Aldosterone",
      "Corticosterone",
      "Follicle Stimulating Hormone",
      "Insulin",
      "Prohormone",
      "Mineral Imbalances",
      "Sodium Ions",
    ],
  },
};

exports.lab_tests = {
  C: ["Serum Calcium", "Iron", "TLC, DLC ,ESR", " Omega 7 Fatty Acid"],
  "C♯": ["Vitamin B1", "Zinc", "Chloride ion", " Omega 3Fatty Acid", " Troponin A"],
  D: ["Vitamin A", "Blood PH", "TLC, DLC ,ESR", " Kidney Function Tests"],
  "D♯": ["Dopamine & Seratonin", "Potassium ", "Blood Cholesterol ", " Thyroid Function Tests"],
  E: ["Riboflavine", "Blood Sugar Fasting", "Liver Function Tests"],
  F: ["Vitamin C", "Copper", "Troponin A", " Complete Lipid Profile"],
  "F♯": ["Serum Sodium", "Serum Potassium", "Serum Cortisol", " Serum Insulin"],
  G: ["Serum Calcium", "Phosphates", "Thyroid function Tests", "Vitamin D", "Kidney function Tests "],
  "G♯": ["Vitamin B6", "Magnesium", "Chromium"],
  A: ["Vitamin B5", "Vitamin E", " Complete Lipid Profile"],
  "A♯": ["Interleukin I & II", "Melatonin ", "Vitamin K "],
  B: ["Vitamin B3", "Biotin", "Troponin A ", " Amino Acid Cysteine"],
};

exports.immunity = {
  Thymus: { fq: "F", color: "#0E9952" },
  "Bone Marrow": { fq: "C", color: "#EE2029" },
  Spleen: { fq: "A♯", color: "#6F58AB" },
  "Lymphatic System": { fq: "A♯", color: "#4F3798" },
  "Compliment System": { fq: "E", color: "#F58C14" },
  "Lymphocytes / Antibodies": { fq: "D", color: "#F2701E" },
  Tonsils: { fq: "G", color: "#1AB7F3" },
};

exports.bloodElemets = {
  minrals: {
    A: "2",
    "A♯": "0",
    B: "1",
    C: "2",
    "C♯": "2",
    D: "1",
    "D♯": "2",
    E: "0",
    F: "2",
    G: "3",
    "G♯": "2",
    "F♯": "1",
    sum: "18",
    color: "#EE2029",
    label: "Minrals",
  },
  hormons: {
    A: "3",
    "A♯": "3",
    B: "2",
    C: "0",
    "C♯": "3",
    D: "3",
    "D♯": "4",
    E: "2",
    F: "1",
    G: "1",
    "G♯": "2",
    "F♯": "1",
    sum: "32",
    color: "#F58C14",
    label: "Hormons",
  },
  neuroTansmitters: {
    A: "3",
    "A♯": "3",
    B: "0",
    C: "0",
    "C♯": "2",
    D: "1",
    "D♯": "4",
    E: "2",
    F: "1",
    G: "1",
    "G♯": "2",
    "F♯": "1",
    sum: "20",
    color: "#FEF100",
    label: "Neuro Tansmitters",
  },
  vitamis: {
    A: "4",
    "A♯": "4",
    B: "4",
    C: "2",
    "C♯": "2",
    D: "3",
    "D♯": "0",
    E: "3",
    F: "2",
    G: "2",
    "G♯": "2",
    "F♯": "2",
    sum: "30",
    color: "#0E9952",
    label: "Vitamis",
  },
  aminoAcod: {
    A: "1",
    "A♯": "2",
    B: "1",
    C: "4",
    "C♯": "0",
    D: "4",
    "D♯": "1",
    E: "1",
    F: "2",
    G: "0",
    "G♯": "1",
    "F♯": "1",
    sum: "18",
    color: "#1AB7F3",
    label: "Amino Acod",
  },
  sum: "118",
  specialTest: {
    A: ["Cholesterol lipids"],
    "A♯": ["Vitamin D"],
    B: ["Pitutary Hormones"],
    C: ["Erythropoietin", "Omega 7", "Fatty Acid"],
    "C♯": [],
    D: ["Kidney function", "Erythropoietin"],
    "D♯": "Thyroid Hormones",
    E: ["Blood Sugar Fasting", "Other Tests for Diabetes", "Liver Function Tests"],
    F: ["Complete lipid Profile"],
    G: ["Thyroid Function Tests", "Kidney Function Tests"],
    "G♯": [],
    "F♯": ["Serum Insulin"],
  },
};
