const wav_files = {
    1: {
        A: "OCTAVE1/A-MAJ1.mp3",
        "A♯": "OCTAVE1/A-SHARP1.mp3",
        B: "OCTAVE1/B-MAJ1.mp3",
        C: "OCTAVE1/C-MAJ1.mp3",
        "C♯": "OCTAVE1/C-SHARP1.mp3",
        D: "OCTAVE1/D-MAJ1.mp3",
        "D♯": "OCTAVE1/D-SHARP1.mp3",
        E: "OCTAVE1/E-MAJ1.mp3",
        F: "OCTAVE1/F-MAJ1.mp3",
        G: "OCTAVE1/G-MAJ1.mp3",
        "G♯": "OCTAVE1/G-SHARP1.mp3",
        "F♯": "OCTAVE1/F-SHARP1.mp3",
    },
    2: {
        A: "OCTAVE2/A-MAJOR2.mp3",
        "A♯": "OCTAVE2/A-SHARP2.mp3",
        B: "OCTAVE2/B-MAJOR2.mp3",
        C: "OCTAVE2/C-MAJ2.mp3",
        "C♯": "OCTAVE2/C-SHARP2.mp3",
        D: "OCTAVE2/D-MAJOR2.mp3",
        "D♯": "OCTAVE2/D-SHARP2.mp3",
        E: "OCTAVE2/E-MAJOR2.mp3",
        F: "OCTAVE2/F-MAJOR2.mp3",
        "F♯": "OCTAVE2/F-SHARP2.mp3",
        G: "OCTAVE2/G-MAJOR2.mp3",
        "G♯": "OCTAVE2/G-SHARP2.mp3",
    },
    3: {
        A: "OCTAVE3/A-MAJOR3.mp3",
        "A♯": "OCTAVE3/A-SHARP3.mp3",
        B: "OCTAVE3/B-MAJOR3.mp3",
        C: "OCTAVE3/C-MAJ3.mp3",
        "C♯": "OCTAVE3/C-SHARP3.mp3",
        D: "OCTAVE3/D-MAJOR3.mp3",
        "D♯": "OCTAVE3/D-SHARP3.mp3",
        E: "OCTAVE3/E-MAJOR3.mp3",
        F: "OCTAVE3/F-MAJOR3.mp3",
        "F♯": "OCTAVE3/F-SHARP3.mp3",
        G: "OCTAVE3/G-MAJOR3.mp3",
        "G♯": "OCTAVE3/G-SHARP3.mp3",
    },
    4: {
        A: "OCTAVE4/A-MAJOR4.mp3",
        "A♯": "OCTAVE4/A-SHARP4.mp3",
        B: "OCTAVE4/B-MAJOR4.mp3",
        C: "OCTAVE4/C-MAJ4.mp3",
        "C♯": "OCTAVE4/C-SHARP4.mp3",
        D: "OCTAVE4/D-MAJOR4.mp3",
        "D♯": "OCTAVE4/D-SHARP4.mp3",
        E: "OCTAVE4/E-MAJOR4.mp3",
        F: "OCTAVE4/F-MAJOR4.mp3",
        "F♯": "OCTAVE4/F-SHARP4.mp3",
        G: "OCTAVE4/G-MAJOR4.mp3",
        "G♯": "OCTAVE4/G-SHARP4.mp3",
    },
    5: {
        A: "OCTAVE5/A-MAJOR5.mp3",
        "A♯": "OCTAVE5/A-SHARP5.mp3",
        B: "OCTAVE5/B-MAJOR5.mp3",
        C: "OCTAVE5/C-MAJOR5.mp3",
        "C♯": "OCTAVE5/C-SHARP5.mp3",
        D: "OCTAVE5/D-MAJOR5.mp3",
        "D♯": "OCTAVE5/D-SHARP5.mp3",
        E: "OCTAVE5/E-MAJOR5.mp3",
        F: "OCTAVE5/F-MAJOR5.mp3",
        "F♯": "OCTAVE5/F-SHARP5.mp3",
        G: "OCTAVE5/G-MAJOR5.mp3",
        "G♯": "OCTAVE5/G-SHARP5.mp3",
    },
    6: {
        A: "OCTAVE6/A-MAJOR6.mp3",
        "A♯": "OCTAVE6/A-SHARP6.mp3",
        B: "OCTAVE6/B-MAJOR6.mp3",
        C: "OCTAVE6/C-MAJOR6.mp3",
        "C♯": "OCTAVE6/C-SHARP6.mp3",
        D: "OCTAVE6/D-MAJOR6.mp3",
        "D♯": "OCTAVE6/D-SHARP6.mp3",
        E: "OCTAVE6/E-MAJOR6.mp3",
        F: "OCTAVE6/F-MAJOR6.mp3",
        "F♯": "OCTAVE6/F-SHARP6.mp3",
        G: "OCTAVE6/G-MAJOR6.mp3",
        "G♯": "OCTAVE6/G-SHARP6.mp3",
    },
};

module.exports = wav_files;
